Fix `RuntimeException` crash thrown by `MediaMetadataRetriever.setDataSource()`
`MediaMetadataRetriever.setDataSource()` will throw `RuntimeException: status = 0xFFFFFFEA` exception when the file doesn't exist. Since we were only catching `IOException`, this exception causes the app to crash.

#### Crash Log
```
java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
    at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
    at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:153)
    at com.facebook.react.modules.camera.CameraRollManager.putImageInfo(CameraRollManager.java:421)
    at com.facebook.react.modules.camera.CameraRollManager.putEdges(CameraRollManager.java:364)
    at com.facebook.react.modules.camera.CameraRollManager.access$300(CameraRollManager.java:59)
    at com.facebook.react.modules.camera.CameraRollManager$GetPhotosTask.doInBackgroundGuarded(CameraRollManager.java:315)
    at com.facebook.react.modules.camera.CameraRollManager$GetPhotosTask.doInBackgroundGuarded(CameraRollManager.java:247)
    at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:34)
    at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:22)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:353)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```
(StackOverflow Reference)[https://stackoverflow.com/questions/46029813/mediametadataretriever-setdatasourcenative-method-causes-runtimeexception-sta]